### ISSUE TITLE
how's the speed compares with FaceBoxes

### ISSUE THREAD

**Issue by lucasjinreal** [AndrewZhaoLuo/CenterFaceTVMDemo#1]
Seems face boxes running on MacBook just need about 8ms

**Comment by AndrewZhaoLuo** [comment]
Cool, this repo was made as a demo for 2021's TVMCon. I did not try running face boxes.

As for why face boxes might be faster:
1. It might be operating at a smaller image resolution (this repo's centerface is 640x640)
2. It might just be a smaller network/more computationally efficient to run
3. Are you running face boxes on cpu or gpu? This demo runs only on CPU on m1 mac
4. Centerface not only does face detection but also alignment so it is more complicated task

At the end of the day you can always try apply similar step in tuning a face box model and see if things go a lot faster!

**Comment by lucasjinreal** [comment]
@AndrewZhaoLuo thank u, can you share M1 Pro cpu speed (time) on tvm? with or without nms?

I have some baseline on SCRFD and Faceboxes runing on cpu onnxruntime.

**Comment by AndrewZhaoLuo** [comment]
Without nms 22.3274 ms on 640x640 image RGB image

**Comment by lucasjinreal** [comment]
@AndrewZhaoLuo SCRFD model runs 512x512 speed at 9ms on onnxruntime....

**Comment by AndrewZhaoLuo** [comment]
Cool, are you simply trying to find the fastest model? There is a lot that goes into this, mostly just backbone + accuracy. 

If you are making a comparison of different face detectors, to be fair you have to take these things into account (probably mostly accuracy). You are welcome to run SCRFD through tvm and probably see some faster speeds 🚀. Pretty confident TVM can beat onnxruntime on m1 mac for most models.

**Comment by lucasjinreal** [comment]
@AndrewZhaoLuo very good advice, will try tvm on scrfd.
how long it takes average for tvm find a fastest model run on M1?

**Comment by AndrewZhaoLuo** [comment]
I just tuned it overnight so ~12 hrs.

**Comment by AndrewZhaoLuo** [comment]
Please let me know results, I am very curious!

**Comment by lucasjinreal** [comment]
@AndrewZhaoLuo I also have a non-technical question about tvm. Since tvm trends to found on specific device and get that device fastest model. What if I am creating a product that will delivered to many users? I need prepare many different models for possible devices? that not make very sense.

how to use tvm in such situation?

**Comment by AndrewZhaoLuo** [comment]
Yes, for each model you need to retune for that specific device. This is the same with existing runtime libraries. OnnxRT under the hood for example, may have multiple implementations depending on whether you are using Nvidia GPU, ARM, x86, etc. That being said, if it is the same hardware inside, you can probably not care.

Anyway, speaking from experience, the most important thing is accuracy in most products I've worked on. I have no doubt the SCRFD model you get can run fast, but maybe a version of the model with a beefier backbone may perform better accuracy. In my experience in the field it can be hard to translate academic accuracy benchmarks into real world product needs so sometimes it may be preferable to have several models of varying "accuracy/capability" on hand just in case for demoing.

What things like TVM do is push the odds in your favor. You may find that you really need that super beefy backbone (e.g. to detect faces at very far distances) but the moment you do your model is now too slow. With TVM, maybe it is fast enough now.

**Comment by lucasjinreal** [comment]
@AndrewZhaoLuo thank u for your clarification, it was helpful. Indeed, we need some various model in hands to solve different real-world scenarios.

I have another question wanna ask, if I optimized a model on iPhone12, does it also applicable on iPhone13 as well using tvm? I mean, does same Phone brand can generalize well with tvm optimization?

**Comment by AndrewZhaoLuo** [comment]
It depends on the underlying hardware more so than anything else. 

I'm guessing that iPhone13 in general has backward compatibility with iPhone12 so you can tune for 12 and go for 13. However if you tune for 13 you may not be able to use it on 12. Tuning for 13 might make things faster however since you may be able to use an updated instruction set. 

In general you'll just have to look at the spec sheets for them both and look at the ISA they are on.
