### ISSUE TITLE
Run python_demo.py got error

### ISSUE THREAD

**Issue by lucasjinreal** [AndrewZhaoLuo/CenterFaceTVMDemo#2]
```
tvm/build/libtvm.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libtvm.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libtvm.dylib' (no such file)

```

I finally successfully built tvm on M1, but run your demo got error, what did I miss?

**Comment by AndrewZhaoLuo** [comment]
Hmm not sure, I'll take a look tomorrow

**Comment by AndrewZhaoLuo** [comment]
Hmm based on the error message it seems to expect an x86_64 chip for tvm. How did you install tvm?

**Comment by lucasjinreal** [comment]
I managed to solve it by switching Conda python to miniforege, it seems m1 Mac Conda shipped is just a x86 python... 
Did u also using Miniforge or just system python?

**Comment by AndrewZhaoLuo** [comment]
I used miniforge
